name: hid
description: A multi-platform plugin which allows an application to interface with USB HID-Class devices on Linux, Windows, Android, and macOS.
version: 0.1.6
repository: https://github.com/rustui/hid/tree/main/hid

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hid_platform_interface: ^0.0.8
  hid_windows: ^0.1.0
  hid_macos: ^0.1.1
  hid_linux: ^0.1.0
  hid_android: ^0.1.3
  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
      platforms:
        windows:
          default_package: hid_windows
        macos:
          default_package: hid_macos
        android:
          default_package: hid_android
        linux:
          default_package: hid_linux
